name: weather_app
description: Job interview application
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # GET
  get: ^4.6.2
  get_storage: ^2.1.1
  # FONT
  google_fonts: ^6.1.0
  auto_size_text: ^3.0.0
  # DIO
  dio: ^5.3.3
  # DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  #TIME
  flutter_datetime_picker: ^1.5.1
  #SYSTEM
  flutter_native_splash: ^2.3.0
  json_theme: ^6.3.0
  image_picker: ^1.0.5
  path_provider: ^2.1.1
  #DISPLAY
  gap: ^3.0.1
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1
  build_runner: any

dependency_overrides:
  intl: ^0.18.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/themes/
    - assets/locales/
    - assets/fake_data/
    - assets/categories/